// Generated by CoffeeScript 1.6.2
(function() {
  var express, fs, oauth, sys, util;

  express = require("express");

  sys = require("sys");

  util = require("util");

  oauth = require("oauth");

  fs = require("fs");

}).call(this);
